# Subsystem: docs/subsystems/orchestrator - Parallel agent orchestration
# Chunk: docs/chunks/scheduler_decompose - Extracted from scheduler.py for single-responsibility
"""Review phase output parsing and configuration.

This module handles parsing of review phase output and loading reviewer
configuration:
- Parsing YAML decision blocks from /chunk-review skill output
- Creating REVIEW_FEEDBACK.md files with reviewer feedback
- Loading reviewer configuration from METADATA.yaml

Extracted from scheduler.py to keep the scheduler focused on dispatch logic.
"""

import logging
import re
from pathlib import Path
from typing import Optional

import yaml

from orchestrator.models import ReviewDecision, ReviewIssue, ReviewResult

logger = logging.getLogger(__name__)


# Chunk: docs/chunks/orch_review_phase - Creates REVIEW_FEEDBACK.md with reviewer feedback for implementer
def create_review_feedback_file(
    worktree_path: Path,
    chunk: str,
    feedback: ReviewResult,
    iteration: int,
) -> Path:
    """Create the REVIEW_FEEDBACK.md file with reviewer feedback.

    This file is written to the chunk directory and contains the reviewer's
    feedback for the implementer to address on the next iteration.

    Args:
        worktree_path: Path to the worktree
        chunk: Chunk directory name
        feedback: ReviewResult containing the feedback details
        iteration: Current review iteration count

    Returns:
        Path to the created feedback file
    """
    feedback_path = worktree_path / "docs" / "chunks" / chunk / "REVIEW_FEEDBACK.md"

    # Build the issues section
    issues_text = ""
    if feedback.issues:
        issues_text = "\n## Issues to Address\n\n"
        for i, issue in enumerate(feedback.issues, 1):
            issues_text += f"### Issue {i}: {issue.location}\n\n"
            issues_text += f"**Concern:** {issue.concern}\n\n"
            if issue.suggestion:
                issues_text += f"**Suggestion:** {issue.suggestion}\n\n"

    content = f"""# Review Feedback

**Iteration:** {iteration}
**Decision:** {feedback.decision.value}

## Summary

{feedback.summary}
{issues_text}
---

This file was generated by the orchestrator's review phase.
The implementer should address the issues above before the next review cycle.
"""

    feedback_path.write_text(content)
    logger.info(f"Created review feedback file: {feedback_path}")

    return feedback_path


# Chunk: docs/chunks/orch_review_feedback_fidelity - Validate that review feedback has been addressed
def validate_feedback_addressed(
    worktree_path: Path,
    chunk: str,
) -> bool:
    """Check whether review feedback has been addressed.

    The implementer signals completion by deleting REVIEW_FEEDBACK.md.
    If the file still exists, feedback has not been fully addressed.

    Args:
        worktree_path: Path to the worktree
        chunk: Chunk directory name

    Returns:
        True if feedback was addressed (file deleted), False otherwise
    """
    feedback_path = worktree_path / "docs" / "chunks" / chunk / "REVIEW_FEEDBACK.md"
    return not feedback_path.exists()


# Chunk: docs/chunks/orch_review_phase - Parse YAML decision block from /chunk-review skill output
def parse_review_decision(agent_output: str) -> Optional[ReviewResult]:
    """Parse the YAML decision block from the /chunk-review skill output.

    The /chunk-review skill outputs a YAML block with the decision:
    ```yaml
    decision: APPROVE|FEEDBACK|ESCALATE
    summary: ...
    issues: [...]
    reason: ...
    iteration: N
    ```

    Args:
        agent_output: The raw text output from the agent

    Returns:
        ReviewResult if successfully parsed, None if parsing fails
    """
    # Look for YAML block markers in the output
    # Pattern 1: Code fence with yaml marker
    yaml_pattern = r"```(?:yaml)?\s*\n(.*?)\n```"
    matches = re.findall(yaml_pattern, agent_output, re.DOTALL)

    for match in matches:
        try:
            data = yaml.safe_load(match)
            if isinstance(data, dict) and "decision" in data:
                # Parse the decision
                decision_str = data.get("decision", "").upper()
                if decision_str not in [d.value for d in ReviewDecision]:
                    continue

                # Parse issues if present
                issues = []
                raw_issues = data.get("issues", [])
                if isinstance(raw_issues, list):
                    for raw_issue in raw_issues:
                        if isinstance(raw_issue, dict):
                            issues.append(ReviewIssue(
                                location=raw_issue.get("location", "unknown"),
                                concern=raw_issue.get("concern", ""),
                                suggestion=raw_issue.get("suggestion"),
                            ))

                return ReviewResult(
                    decision=ReviewDecision(decision_str),
                    summary=data.get("summary", "No summary provided"),
                    issues=issues,
                    reason=data.get("reason"),
                    iteration=data.get("iteration", 1),
                )
        except yaml.YAMLError:
            continue

    # Pattern 2: Look for decision: line directly (fallback for simpler output)
    decision_line_pattern = r"^\s*decision:\s*(APPROVE|FEEDBACK|ESCALATE)\s*$"
    match = re.search(decision_line_pattern, agent_output, re.MULTILINE | re.IGNORECASE)
    if match:
        decision_str = match.group(1).upper()
        return ReviewResult(
            decision=ReviewDecision(decision_str),
            summary="Decision parsed from output (no YAML block found)",
        )

    return None


# Chunk: docs/chunks/orch_review_phase - Load reviewer config for loop detection settings
def load_reviewer_config(project_dir: Path, reviewer: str = "baseline") -> dict:
    """Load reviewer configuration from METADATA.yaml.

    Args:
        project_dir: Project root directory
        reviewer: Reviewer name (default: "baseline")

    Returns:
        Dict with reviewer config, including loop_detection settings
    """
    metadata_path = project_dir / "docs" / "reviewers" / reviewer / "METADATA.yaml"

    defaults = {
        "loop_detection": {
            "max_iterations": 3,
            "escalation_threshold": 2,
            "same_issue_threshold": 2,
        }
    }

    if not metadata_path.exists():
        logger.warning(f"Reviewer config not found: {metadata_path}, using defaults")
        return defaults

    try:
        with open(metadata_path) as f:
            config = yaml.safe_load(f) or {}

        # Merge with defaults
        loop_detection = config.get("loop_detection", {})
        return {
            "name": config.get("name", reviewer),
            "loop_detection": {
                "max_iterations": loop_detection.get("max_iterations", 3),
                "escalation_threshold": loop_detection.get("escalation_threshold", 2),
                "same_issue_threshold": loop_detection.get("same_issue_threshold", 2),
            },
        }
    except Exception as e:
        logger.warning(f"Error loading reviewer config: {e}, using defaults")
        return defaults
