// Chunk: docs/chunks/gateway_cleartext_api - Gateway crypto tests
/**
 * Tests for the gateway crypto module.
 * Verifies wire compatibility with the Python src/board/crypto.py.
 */
import { describe, it, expect } from "vitest";
import {
  hashToken,
  decryptBlob,
  deriveTokenKey,
  deriveSymmetricKey,
  decryptMessage,
  encryptMessage,
} from "../src/gateway-crypto";

// Cross-language test vectors generated by Python crypto.py
// See: docs/chunks/gateway_cleartext_api/generate-test-vectors.py
const VECTORS = {
  seed_hex: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  curve25519_private_hex:
    "00df8dd9e9eac760a1b68c1565388b1e93049b155baa8808cf4b4985f8665b68",
  symmetric_key_hex:
    "79e3c150b7996add372bfb6b4bf7f94f10fd0e3bc9fcbdfaafa9da48db2ce957",
  plaintext: "hello from python",
  fixed_nonce_ciphertext_b64:
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBvhqMJc5tERgAxusY76ER3s3IFCZFyHGGFbrQjXsKSdTG",
  random_nonce_ciphertext_b64:
    "mwPQCtPEY/Gkpt3ONPqTISLg5mXJWsGfOl+DJNfqmw6jv64/Pae848hxrKGboSNAm02n/4awMehV",
  token_hex: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  // Chunk: docs/chunks/invite_token_instant_expiry - Corrected vectors (raw-byte hash + HKDF key)
  token_hash_hex:
    "4ca14526b2751b640d549ce7caf8ac39438592211a0ec370064d57666a682ad6",
  token_key_hex:
    "ec8c9b12053980130f321ce7e7613775de59755214bb873e35b809c1865bad5a",
  encrypted_blob_b64:
    "AgICAgICAgICAgICAgICAgICAgICAgICop3njUFozEwpiOPNZVfB1olQjRm3/clmci/ow1PZ4lf/JB9b/s/l+Hy5iyQ6+iqj7txHdxJEel4TZSyS3KLsvw0doQO6ZrMn2NC2VgrHAbo=",
};

function hexToBytes(hex: string): Uint8Array {
  return new Uint8Array(hex.match(/.{2}/g)!.map((h) => parseInt(h, 16)));
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

describe("Gateway crypto", () => {
  describe("hashToken", () => {
    it("computes SHA-256 of the raw token bytes (cross-language vector)", () => {
      const hash = hashToken(VECTORS.token_hex);
      expect(hash).toBe(VECTORS.token_hash_hex);
    });
  });

  describe("deriveTokenKey", () => {
    it("derives HKDF key matching Python derive_token_key (cross-language vector)", () => {
      const key = deriveTokenKey(VECTORS.token_hex);
      expect(bytesToHex(key)).toBe(VECTORS.token_key_hex);
    });
  });

  describe("deriveSymmetricKey", () => {
    it("produces the same key as Python crypto.py (cross-language vector)", () => {
      const seed = hexToBytes(VECTORS.seed_hex);
      const key = deriveSymmetricKey(seed);
      expect(bytesToHex(key)).toBe(VECTORS.symmetric_key_hex);
    });

    it("is deterministic", () => {
      const seed = hexToBytes(VECTORS.seed_hex);
      const key1 = deriveSymmetricKey(seed);
      const key2 = deriveSymmetricKey(seed);
      expect(bytesToHex(key1)).toBe(bytesToHex(key2));
    });
  });

  describe("decryptBlob", () => {
    it("recovers the seed from a Python-encrypted blob (HKDF key derivation)", () => {
      const plaintext = decryptBlob(VECTORS.encrypted_blob_b64, VECTORS.token_hex);
      // Python encrypts seed.hex() as UTF-8 string, so plaintext is the hex string
      expect(new TextDecoder().decode(plaintext)).toBe(VECTORS.seed_hex);
    });

    it("throws on wrong token", () => {
      const wrongToken =
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
      expect(() => decryptBlob(VECTORS.encrypted_blob_b64, wrongToken)).toThrow();
    });

    it("throws on truncated blob", () => {
      expect(() => decryptBlob("AQID", VECTORS.token_hex)).toThrow();
    });
  });

  describe("decryptMessage", () => {
    it("decrypts a Python-encrypted message (fixed nonce vector)", () => {
      const key = hexToBytes(VECTORS.symmetric_key_hex);
      const plaintext = decryptMessage(VECTORS.fixed_nonce_ciphertext_b64, key);
      expect(plaintext).toBe(VECTORS.plaintext);
    });

    it("decrypts a Python-encrypted message (random nonce vector)", () => {
      const key = hexToBytes(VECTORS.symmetric_key_hex);
      const plaintext = decryptMessage(VECTORS.random_nonce_ciphertext_b64, key);
      expect(plaintext).toBe(VECTORS.plaintext);
    });

    it("throws on wrong key", () => {
      const wrongKey = new Uint8Array(32); // all zeros
      expect(() =>
        decryptMessage(VECTORS.fixed_nonce_ciphertext_b64, wrongKey)
      ).toThrow();
    });
  });

  describe("encryptMessage / decryptMessage round-trip", () => {
    it("encrypt then decrypt returns original plaintext", () => {
      const key = hexToBytes(VECTORS.symmetric_key_hex);
      const plaintext = "round trip test message";
      const ciphertext = encryptMessage(plaintext, key);
      const decrypted = decryptMessage(ciphertext, key);
      expect(decrypted).toBe(plaintext);
    });

    it("each encryption produces different ciphertext (random nonce)", () => {
      const key = hexToBytes(VECTORS.symmetric_key_hex);
      const plaintext = "nonce test";
      const ct1 = encryptMessage(plaintext, key);
      const ct2 = encryptMessage(plaintext, key);
      expect(ct1).not.toBe(ct2);
      // Both decrypt to same plaintext
      expect(decryptMessage(ct1, key)).toBe(plaintext);
      expect(decryptMessage(ct2, key)).toBe(plaintext);
    });
  });

  describe("full pipeline: token → blob → seed → symmetric key → message crypto", () => {
    it("decrypts blob, derives key, then decrypts message", () => {
      // Recover seed hex from blob (Python encrypts seed.hex() as UTF-8)
      const plaintext = decryptBlob(VECTORS.encrypted_blob_b64, VECTORS.token_hex);
      const seedHex = new TextDecoder().decode(plaintext);
      expect(seedHex).toBe(VECTORS.seed_hex);

      // Derive symmetric key from seed bytes
      const seed = hexToBytes(seedHex);
      const key = deriveSymmetricKey(seed);
      expect(bytesToHex(key)).toBe(VECTORS.symmetric_key_hex);

      // Decrypt a Python-encrypted message
      const msg = decryptMessage(VECTORS.fixed_nonce_ciphertext_b64, key);
      expect(msg).toBe(VECTORS.plaintext);
    });
  });

  // Chunk: docs/chunks/invite_token_instant_expiry - Cross-language invite token vectors
  describe("cross-language invite token vectors", () => {
    it("hashToken produces same hash as Python SHA256(raw_bytes)", () => {
      // Python: hashlib.sha256(bytes.fromhex(token_hex)).hexdigest()
      const hash = hashToken(VECTORS.token_hex);
      expect(hash).toBe(VECTORS.token_hash_hex);
    });

    it("deriveTokenKey produces same key as Python derive_token_key", () => {
      // Python: derive_token_key(bytes.fromhex(token_hex))
      const key = deriveTokenKey(VECTORS.token_hex);
      expect(bytesToHex(key)).toBe(VECTORS.token_key_hex);
    });

    it("decryptBlob recovers seed from Python-encrypted blob", () => {
      // Python: SecretBox(derive_token_key(token)).encrypt(seed.hex().encode(), nonce)
      const plaintext = decryptBlob(VECTORS.encrypted_blob_b64, VECTORS.token_hex);
      expect(new TextDecoder().decode(plaintext)).toBe(VECTORS.seed_hex);
    });
  });
});
